"""empty message

Revision ID: 301221f6afc6
Revises: ba5c9af74501
Create Date: 2022-10-24 16:22:02.507148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301221f6afc6'
down_revision = 'ba5c9af74501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'description')
    # ### end Alembic commands ###
